import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { root,config,run } from '../scripts/common.mjs';
import { sha256 } from '../scripts/hash.mjs';
import { archiveEntrySha256 } from '../scripts/archive-hash.mjs';

test('runtime installation verifies identity and content before accepting an archive', {skip:process.platform!=='darwin'}, async t=>{
  const dir=mkdtempSync(path.join(tmpdir(),'hybrid-tooling-test-'));
  t.after(()=>rmSync(dir,{recursive:true,force:true}));
  const release=path.join(dir,'release'); mkdirSync(release);
  const entry='Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework';
  const framework=path.join(dir,'input',entry);
  mkdirSync(path.dirname(framework),{recursive:true});
  writeFileSync(framework,'test fixture, not an executable');
  const filename=`electron-${config.releaseTag}-${config.platform}-${config.arch}.zip`;
  const archive=path.join(release,filename);
  run('ditto',['-c','-k','--keepParent',path.join(dir,'input','Electron.app'),archive]);
  const expectedHash=await sha256(framework);
  assert.equal(await archiveEntrySha256(archive,entry),expectedHash);
  await assert.rejects(archiveEntrySha256(archive,'missing-entry'));
  const manifest={...config,filename,sha256:await sha256(archive),binarySha256:expectedHash};
  const save=value=>writeFileSync(path.join(release,'manifest.json'),JSON.stringify(value));
  const install=dest=>spawnSync(process.execPath,[path.join(root,'scripts/install-runtime.mjs'),dest,release],{encoding:'utf8'});
  const bad=path.join(dir,'bad');
  save({...manifest,electronVersion:'0.0.0'});
  assert.notEqual(install(bad).status,0); assert.equal(existsSync(bad),false);
  save({...manifest,filename:'../unexpected.zip'});
  assert.notEqual(install(bad).status,0); assert.equal(existsSync(bad),false);
  save({...manifest,sha256:'0'.repeat(64)});
  assert.notEqual(install(bad).status,0); assert.equal(existsSync(bad),false);
  save({...manifest,binarySha256:'0'.repeat(64)});
  assert.notEqual(install(bad).status,0); assert.equal(existsSync(bad),false);
  save(manifest);
  const destination=path.join(dir,'installed');
  const valid=install(destination);
  assert.equal(valid.status,0,valid.stderr);
  assert.equal(readFileSync(path.join(destination,entry),'utf8'),'test fixture, not an executable');
  writeFileSync(path.join(destination,'sentinel'),'preserve me');
  assert.notEqual(install(destination).status,0);
  assert.equal(readFileSync(path.join(destination,'sentinel'),'utf8'),'preserve me');
});
